services:
  jupyter:
    image: miquelmarinoespinosa/jupyter-python-machine-learning
    #build:
    #  context: .
    ports:
      - 8889:8888
    volumes:
      - ./work:/home/jovyan/work
    command: start-notebook.py --NotebookApp.token='my-token'
